# Generated by Django 3.2.4 on 2021-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('book_details', models.CharField(max_length=300)),
                ('book_author', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='book_images/')),
                ('book_path', models.ImageField(upload_to='book_path/')),
            ],
        ),
    ]
